### ISSUE TITLE
Full frames with subarray holes

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_pipeline#15]
Unlike JWST, IRIS will be able to concurrently readout the subarrays (up to 10 rectangular, any location, any size, not overlapping), and the rest of the frame.

Therefore we will have to process frames which are full except those rectangular holes, and then somehow combine them back properly into a single frame.

Plan is to have a FITS extension, 16 bits, so 1-10 will be identifying which pixel is part of which subarray. It is 32MB for this, compared to 64MB of data, however this is only when we are running with subarrays, so should be fine.

```
    subarrays:
      title: Subarray mask
      fits_hdu: SUBARRMASK                                                                  
      default: 0
      datatype: uint16
```

I also think we should have one bit of the standard `DQ` mask which indicates that a pixel is part of any subarray, so that it is handled exactly like dead pixels and so on. So the pipeline should be already able to just process it (will test it).

@arunsurya77 @ikashell any comment?
